# Generated by Django 5.2.5 on 2025-09-04 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LizardAccounts', '0004_remove_confidentialasset_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lizards',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lizards',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lizards',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
